### ISSUE TITLE
30.11. Session

### ISSUE THREAD

**Issue by marekprochazka** [FIT-prasata/IFJ-2022#70]
- [x] #7: @TheSkleny 
- [x] #52 + is_it_ok.sh: @marekprochazka 
- [x] #56 (start unit tests flow): @marekprochazka 
- [x] Analyze student's E2E tests: @marekprochazka 
- [x] #57: @lukaszavadil1 
- [x] #67 (precedence table visualisation + header file): @lukaszavadil1 
- [x] #68: @lukaszavadil1 
- [x] #64 (goal will be set in the morning): @AdamSvetlik  + @TheSkleny 
- [x] #69 (analyze): @TheSkleny
